# Generated by Django 5.2.11 on 2026-02-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subscription_status', models.BooleanField(default=False)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_flags.featureflag')),
            ],
        ),
        migrations.CreateModel(
            name='RegionFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('enabled', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_flags.featureflag')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_flags.featureflag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature_flags.user')),
            ],
        ),
    ]
