# Generated by Django 5.2.11 on 2026-02-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc123', max_length=100),
            preserve_default=False,
        ),
    ]
