# Generated by Django 5.2.11 on 2026-02-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
