# Generated by Django 5.2.11 on 2026-02-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0003_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionfeatureoverride',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
