# Generated by Django 5.2.11 on 2026-02-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0004_regionfeatureoverride_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionfeatureoverride',
            name='movie_name',
        ),
    ]
