# Generated by Django 5.2.11 on 2026-02-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0005_remove_regionfeatureoverride_movie_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupfeatureoverride',
            unique_together={('group_name', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('region', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='regionfeatureoverride',
            unique_together={('region', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='userfeatureoverride',
            unique_together={('user', 'feature')},
        ),
    ]
